import ts from 'typescript';
import fs from 'node:fs';
import path from 'node:path';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP (pure-JS fallback for noexec/HarmonyOS env)
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Inline TS transpile using the project's own typescript (pure JS, no native binary)
const tsPlugin = {
  name: 'ts-transpile',
  resolveId(source, importer) {
    if (!importer) return null;
    if (source.startsWith('.') || source.startsWith('/')) {
      const base = path.resolve(path.dirname(importer), source);
      const candidates = ['.ts', '.js', '/index.ts', '/index.js'];
      for (const c of candidates) {
        if (fs.existsSync(base + c)) return base + c;
      }
    }
    return null;
  },
  transform(code, id) {
    if (!id.endsWith('.ts')) return null;
    const out = ts.transpileModule(code, {
      compilerOptions: {
        module: ts.ModuleKind.ESNext,
        target: ts.ScriptTarget.ES2021,
        esModuleInterop: true,
        isolatedModules: true,
        sourceMap: false,
      },
      fileName: id,
    });
    return {
      code: out.outputText,
      map: out.sourceMapText ? JSON.parse(out.sourceMapText) : null,
    };
  },
};

// Treat every bare import (obsidian, electron, @codemirror/*, @lezer/*, node builtins) as external
const isExternal = (id) =>
  !id.startsWith('.') && !id.startsWith('/') && !path.isAbsolute(id);

export default {
  input: 'src/main.ts',
  output: {
    file: 'main.js',
    format: 'cjs',
    banner,
    exports: 'auto',
    sourcemap: false,
    inlineDynamicImports: true,
  },
  external: (id) => isExternal(id) || builtinModules.includes(id),
  plugins: [tsPlugin],
  onwarn(warning, warn) {
    // ignore circular / unknown-onload noise from transpile-only mode
    if (warning.code === 'CIRCULAR_DEPENDENCY') return;
    warn(warning);
  },
};
